// Central Route Audit List (FASE 13)
// This file acts as a checklist for all the registered and expected Giffoni Connect BOSS Routes.

export const expectedRoutes = [
  // GRUPO 1 — ROTAS BASE
  '/',
  '/boss-giffoni-clientes/login',
  '/boss-giffoni-clientes/login-lite',
  '/boss-giffoni-clientes/dashboard',
  '/boss-giffoni-clientes/central-controle',
  '/boss-giffoni-clientes/setores',
  '/boss-giffoni-clientes/setores/dashboard.RH.Giffoni.Adv.Associados',
  '/boss-giffoni-clientes/configuracoes',
  '/boss-giffoni-clientes/giffoni-connect-atalhos',

  // GRUPO 2 — CONFIGURAÇÕES E INTEGRAÇÕES
  '/boss-giffoni-clientes/configuracoes/integracoes-stripe',
  '/boss-giffoni-clientes/configuracoes/integracoes-asaas',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-drive',
  '/boss-giffoni-clientes/configuracoes/integracoes-todoist',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-calendar',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-gerais-google-docs',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-procuracao-PF',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-procuracao-PJ',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-declaracao-PF',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-declaracao-PJ',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-contrato-de-honorarios-PF',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-contrato-de-honorarios-PJ',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-1-atendimento-PF',
  '/boss-giffoni-clientes/configuracoes/integracoes-google-docs/config-1-atendimento-PJ',
  '/boss-giffoni-clientes/configuracoes/integracoes-whatsapp',
  '/boss-giffoni-clientes/configuracoes/integracoes-gmail',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos/clientes',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos/casos',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos-clientes',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos-casos',

  // GRUPO 3 — CLIENTES E CASOS
  '/boss-giffoni-clientes/clientes',
  '/boss-giffoni-clientes/clientes/novo',
  '/boss-giffoni-clientes/clientes/:clientId',
  '/boss-giffoni-clientes/casos',
  '/boss-giffoni-clientes/casos/novo',
  '/boss-giffoni-clientes/casos/:caseId',

  // GRUPO 4 — PORTAL DO CLIENTE / PREVIEW
  '/boss-giffoni-clientes/portal-editor/:clientId',
  '/boss-giffoni-clientes/portal-preview/:clientSlug',
  '/boss-giffoni-clientes/portal-cliente-preview/:clientId',
  '/boss-giffoni-clientes/fluxo-producao/portal-cliente',
  '/boss-giffoni-clientes/fluxo-producao/editar-portal-cliente/:slug',
  '/portal-cliente-giffoni/:slug/login',
  '/portal-cliente-giffoni/:slug/casos',
  '/portal-cliente-giffoni/:slug/casos/:caseId',

  // GRUPO 5 — FLUXO DE PRODUÇÃO BASE
  '/boss-giffoni-clientes/fluxo-producao',
  '/boss-giffoni-clientes/fluxo-producao/cadastro',
  '/boss-giffoni-clientes/fluxo-producao-exibir-pendencias',
  '/boss-giffoni-clientes/fluxo-producao/recadastramento',
  '/boss-giffoni-clientes/fluxo-producao/tipo-producao',
  '/boss-giffoni-clientes/fluxo-producao/tipo-producao/judicial',
  '/boss-giffoni-clientes/fluxo-producao/tipo-producao/extrajudicial',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/editar-cadastro-cliente',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/judicial',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/extrajudicial',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/peticao-inicial',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/peticao_inicial',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/processo-judicial-em-andamento',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/requerimento-administrativo',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/tipo-producao/outro-servico-administrativo',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/dados-caso',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacoes-informacoes',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacoes-provas',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/card-iniciar-coleta-obrigatoria',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/financeiro',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/financeiro/Criar Contrato de Honorários',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/financeiro/ver.detalhes.do.contrato.de.honorarios',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/financeiro/auditoria.do.contrato.de.honorarios',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/edrp',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/delegacao',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/revisao',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/protocolo',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/compliance',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/novo-caso',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/pre-peticionamento-ia',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/controladoria',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/relatorio-integridade',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/arquivamento',

  // GRUPO 6 — COLETA / DOCUMENTOS / GDI
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-procuracao-PF',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-procuracao-PJ',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-declaracao-PF',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-declaracao-PJ',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-contrato-PF',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-contrato-PJ',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-documentos-minimos-PF',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-documentos-minimos-PJ',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-documentos-necessidade-PF',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-documentos-necessidade-PJ',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-documentos-auditoria-PF',
  '/boss-giffoni-clientes/fluxo-producao/:caseId/solicitacao-documentos-auditoria-PJ',

  // GRUPO 7 — LEADS / MARKETING
  '/boss/leads/private/dashboard',
  '/boss/leads/private/dashboard/repositorio-excluidos',
  '/boss/cadastrar.leads/private',
  '/boss/cadastrar.leads/private/lead-pf',
  '/boss/cadastrar.leads/private/lead-pj',
  '/boss/cadastrar.leads/private/etapa02/:leadId',
  '/boss/cadastrar.leads/private/etapa02/:leadId/viabilidade',

  // GRUPO 8 — ALIASES / COMPATIBILIDADE
  '/boss-giffoni-clientes/configurações',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos/clientes',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos/casos',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos-clientes',
  '/boss-giffoni-clientes/configuracoes/detalhes-tecnicos-casos'
];
